; off | develop | coverage | debug | profile | trace
xdebug.mode = XDEBUG_MODE
xdebug.client_host = XDEBUG_HOST
xdebug.idekey = XDEBUG_IDEKEY
xdebug.start_with_request = trigger
xdebug.connect_timeout_ms = 10000
xdebug.discover_client_host = 1
xdebug.cli_color = 1
xdebug.profiler_output_name = "%t-%s-profile.out"
xdebug.log = /var/log/xdebug.log
xdebug.output_dir = /var/www/xdebug
