; off | develop | coverage | debug | profile | trace
xdebug.mode = XDEBUG_MODE
xdebug.profiler_output_name = "%t-%s-profile.out"
xdebug.cli_color = 1
xdebug.start_with_request = trigger
xdebug.discover_client_host = yes
xdebug.client_host = XDEBUG_HOST
xdebug.idekey = XDEBUG_IDEKEY
xdebug.log = /var/log/xdebug.log
xdebug.output_dir = /var/www/xdebug
xdebug.connect_timeout_ms = 1000

