volumes:
    ssl:
    db:
    phpmyadmin:

networks:
    nginx:

services:
    app:
        image: app
        build:
            context: ./app
            args:
                FZF: ${FZF}
                FISH: ${FISH}
                FDFIND: ${FDFIND}
                PNPM_VERSION: ${PNPM_VERSION}
                NODE: ${NODE}
                NODE_VERSION: ${NODE_VERSION}
                NVM_NODEJS_ORG_MIRROR: ${NVM_NODEJS_ORG_MIRROR}
                NVIM: ${NVIM}
                OHMYFISH: ${OHMYFISH}
                OHMYBASH: ${OHMYBASH}
                WORKDIR: ${WORKDIR}
        restart: always
        working_dir: ${WORKDIR}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # dns:
        #     8.8.8.8
        volumes:
            - ./app/entry.sh:/usr/local/bin/entry.sh
            - ./crontab:/etc/crontabs/www
            - ${MAPDIR}:${WORKDIR}
            - $HOME/.ssh:/home/${APP_USER}/.ssh
            - $HOME/.cache/composer:/composer/cache
        environment:
            NVM_NODEJS_ORG_MIRROR: ${NVM_NODEJS_ORG_MIRROR}
            APP_ENV: ${APP_ENV}
            APP_USER: ${APP_USER}
            APP_DEBUG: ${APP_DEBUG}
            XDEBUG_MODE: ${XDEBUG_MODE}
            XDEBUG_HOST: ${XDEBUG_HOST}
            XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
            XDEBUG_TRIGGER: ${XDEBUG_TRIGGER}
            WORKDIR: ${WORKDIR}
        ports:
            - 25:25
        networks:
            - nginx
        logging:
            driver: json-file
            options:
                max-size: "128m"
                max-file: "1"
        # command: tail -f /dev/null
    nginx:
        extends:
            file: templates.yml
            service: nginx
        image: nginx:stable-alpine3.17
        user: ${UID}:${GID}
        depends_on:
            - app
            - mariadb
            - redis
        build:
            context: nginx
            args:
                - WORKDIR=${WORKDIR}
        restart: always
        volumes:
            - ${MAPDIR}:${WORKDIR}
            - ./nginx/sites:/etc/nginx/sites-available
            - ./nginx/extras:/etc/nginx/extras
            - ssl:/etc/letsencrypt/live
            - phpmyadmin:/var/www/html
        environment:
            - WORKDIR=${WORKDIR}
        ports:
            - 80:80
            - 443:443
        # command: tail -f /dev/null

    mariadb:
        build:
            context: ./mariadb
        image: mariadb:lts
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        networks:
            - nginx
        ports:
            - 3306:3306

    redis:
        build: ./redis
        restart: always
        networks:
            - nginx
        ports:
            - 6379:6379

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:fpm-alpine
        volumes:
            - phpmyadmin:/var/www/html
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: "root"
            PMA_PASSWORD: "secret"
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 10048M  # Large upload limit
            MAX_EXECUTION_TIME: 600  # Increase execution time
            MEMORY_LIMIT: 512M  # Set memory limit as needed
        networks:
            - nginx

    mailhog:
        image: mailhog/mailhog
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - nginx
