https://${APP_URL} {
    root * ${SERVE_ROOT}

    tls /etc/caddy/ssl/${APP_URL}.crt /etc/caddy/ssl/${APP_URL}.key

	# encode zstd br gzip

    # Import WordPress headers
    import /etc/caddy/wordpress_headers.conf


	php_server

}



# Redirect all HTTP to HTTPS
http://${APP_URL} {
    redir https://${APP_URL}{uri}
}
