
@fontFiles {
    path /wp-content/themes/*/*.woff
    path /wp-content/themes/*/*.woff2
    path /wp-content/themes/*/*.ttf
}

header @fontFiles {
    Access-Control-Allow-Origin "https://${APP_URL}"
    Access-Control-Allow-Methods "GET, OPTIONS"
    Access-Control-Allow-Headers "*"
}

@restCors {
    path /wp-json/*
}
header @restCors {
    Access-Control-Allow-Origin "https://localhost:3000"
    Access-Control-Allow-Credentials "true"
    Access-Control-Allow-Headers "Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range, X-WP-Nonce"
    Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH"
}

@restPreflight {
    method OPTIONS
    path /wp-json/*
}
respond @restPreflight 204

@adminPaths {
    path /wp-admin/*
    path /wp-login.php
}
header @adminPaths {
    Access-Control-Allow-Origin "https://localhost:3000"
    Access-Control-Allow-Credentials "true"
    Access-Control-Allow-Headers "Authorization, Accept, Origin, DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Content-Range, Range, X-WP-Nonce"
    Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE, PATCH"
}


@adminPreflight {
    method OPTIONS
    path /wp-admin/*
    path /wp-login.php
}
respond @adminPreflight 204

@staticFiles {
    file
    path /wp-content/uploads/*
    path /wp-content/themes/*
    path /wp-content/plugins/*
}
header @staticFiles Cache-Control "public, max-age=31536000, immutable"
