http://phpmyadmin.test {
    root * /var/www/html
    encode gzip

    file_server

    php_fastcgi phpmyadmin:9000
}

https://phpmyadmin.test {
    tls internal
    redir http://phpmyadmin.test{uri}
}
