server {
    listen                  443 ssl;
    http2 on;

    server_name             ${APP_URL};
    root                    ${NGINX_ROOT};

    # SSL
    ssl_certificate         /etc/letsencrypt/live/${APP_URL}/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/${APP_URL}/privkey.pem;

    # index.php
    index                   index.php index.html index.htm;

    # index.php fallback
    location / {
        try_files  $uri $uri/ /index.php?$query_string;
        # CORS configuration
        add_header 'Access-Control-Allow-Origin' 'https://localhost:3000' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;

        # Preflight requests
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'https://localhost:3000' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    # handle .php
    location ~ \.php$ {
        include             extras/php_fastcgi.conf;
    }

    # ACME-challenge
    location ^~ /.well-known/acme-challenge/ {
        root /var/www;
    }

    # Additional
    # ${WORDPRESS}
}

# Redirect to SSL
server {
    listen      80;
    server_name ${APP_URL};

    return                  301 https://${APP_URL}$request_uri;
}

# Sub Domains Redirect
server {
    listen                  443 ssl;
    http2 on;
    server_name             *.${APP_URL};

    # SSL
    ssl_certificate /etc/letsencrypt/live/${APP_URL}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${APP_URL}/privkey.pem;

    return                  301 https://${APP_URL}$request_uri;
}
