map $request_method $cors_allow_origin {
    default "";
    ~^(GET|POST|PUT|DELETE|OPTIONS)$ "https://localhost:3000";
}

map $request_method $cors_allow_methods {
    default "";
    ~^(GET|POST|PUT|DELETE|OPTIONS)$ "GET, POST, PUT, DELETE, OPTIONS";
}

map $request_method $cors_allow_headers {
    default "";
    ~^(GET|POST|PUT|DELETE|OPTIONS)$ 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-wp-nonce';
}

map $request_method $cors_allow_credentials {
    default "";
    ~^(GET|POST|PUT|DELETE|OPTIONS)$ 'true';
}
